dist: focal
addons:
  apt:
    packages:
      - libomp-dev
      - libtbb-dev
      - libopenblas-openmp-dev

language: cpp
compiler:
  - gcc
branches:
  only:
    - master
    - develop
    - feature/fix_ci
script:
  - cd test/build
  - bash ../../data/mnist/prepare_mnist_dataset.sh
  - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_OPENMP=ON -DUSE_OPENBLAS=ON -DUSE_INTEL_TBB=ON ..
  - make
  - ./test_all_in_one.out
