language: cpp
compiler:
  - gcc
branches:
  only:
    - master
    - develop
script:
  - cd test/build
  - bash ../../data/mnist/prepare_mnist_dataset.sh
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - ./test.out
